spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airTicket
    username:
    password:
    
  jpa:
    datasource-platform: org.hibernate.dialect.PostgreSQLDialect
    
    hibernate:
        ddl-auto: update
      
    show-sql: ture